version: '3.8'

services:
  web:
    build:
      context: ../../dockerfilesVAF/web
      dockerfile: DockerfileVAF
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_NAME=Jardineria
      - DB_PASSWORD=pswJardineria
      - PORT=3000
      - HOST_API=http://localhost:3001/api
      - JWT_SECRET=MIclaveSecreta1
    networks:
      - vaf_network

  db:
    build:
      context: ../../dockerfilesVAF/sgbd
      dockerfile: DockerfileVAF
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pswJardineria
      POSTGRES_DB: Jardineria
    networks:
      - vaf_network

networks:
  vaf_network:
    ipam:
      driver: default
      config:
        - subnet: 172.240.10.0/24
